# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
# Edit here to specify the rust version
channel = "1.80.0"
# IDE-ready component set
profile = "default"
components = ["rust-analyzer", "rust-src"]
targets = []
